services:
  - type: web
    name: xiaoji-lavalink
    runtime: docker
    plan: free
    region: singapore
    rootDir: deploy/lavalink
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: LAVALINK_SERVER_PASSWORD
        sync: false
      - key: _JAVA_OPTIONS
        value: -Xms64m -Xmx384m
    buildFilter:
      paths:
        - deploy/lavalink/**
